# -*- coding: utf-8 -*-
"""Collatz-5_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O10WjxOfNbQ4IbHwt5-dVUVhEjFlPDrs
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Collatz-5: Racing Gliders in Pentadica
Public reference implementation (Python)

Author : Hiroshi Harada
License: CC BY 4.0

This script implements the 5-adic Collatz-type map used in
"Collatz-5: Racing Gliders in Pentadica".

Main features:
- Collatz-5 update rule f(n)
- Orbit generation
- Step / lap / max-value statistics
- Simple P(3,2) filter
- Command-line demo for small ranges
"""

from dataclasses import dataclass
from typing import List, Iterable


# ------------------------------------------------------------
# 1. Core 5-adic Collatz map
# ------------------------------------------------------------

def collatz5_step(n: int) -> int:
    """
    One step of the Collatz-5 map.

    Rules (integer n, based on n mod 5):

        mod 5 = 0 -> f(n) = n / 5
        mod 5 = 1 -> f(n) = (6n - 1) / 5
        mod 5 = 2 -> f(n) = (6n - 2) / 5
        mod 5 = 3 -> f(n) = (6n - 3) / 5
        mod 5 = 4 -> f(n) = (6n + 1) / 5
    """
    r = n % 5
    if r == 0:
        return n // 5
    elif r == 1:
        return (6 * n - 1) // 5
    elif r == 2:
        return (6 * n - 2) // 5
    elif r == 3:
        return (6 * n - 3) // 5
    else:  # r == 4
        return (6 * n + 1) // 5


# ------------------------------------------------------------
# 2. Orbit and statistics
# ------------------------------------------------------------

@dataclass
class OrbitStats:
    start: int
    steps: int
    laps: int
    max_value: int
    orbit: List[int]

    def classification(self) -> str:
        """
        Very simple classifier based on steps, laps, and max_value.
        You can tune thresholds as you like.
        """
        if self.steps < 5:
            return "Instant Drop"
        if self.steps < 20 and self.laps < 10:
            return "Short-Range Glider"
        if self.steps >= 20 and self.laps >= 10 and self.max_value < 10**6:
            return "Endurance Glider"
        if self.max_value >= 10**6 and self.steps >= 50:
            return "High-Altitude Jumper"
        if self.max_value >= 10**8 and self.steps >= 100:
            return "Legendary Glider"
        return "Unclassified"


def collatz5_orbit(n: int, max_steps: int = 10_000) -> OrbitStats:
    """
    Generate the orbit of n under Collatz-5 until it reaches {1, 2, 3}
    or until max_steps is exceeded.

    Returns OrbitStats with:
        - steps: total number of steps
        - laps : number of steps with n mod 5 != 0 (Outer Circuit)
        - max_value: maximum value reached
        - orbit: list of visited values (including start and final)
    """
    if n <= 0:
        raise ValueError("n must be a positive integer")

    orbit = [n]
    laps = 0
    max_value = n
    steps = 0

    current = n
    while current not in (1, 2, 3) and steps < max_steps:
        if current % 5 != 0:
            laps += 1
        current = collatz5_step(current)
        orbit.append(current)
        steps += 1
        if current > max_value:
            max_value = current

    return OrbitStats(
        start=n,
        steps=steps,
        laps=laps,
        max_value=max_value,
        orbit=orbit,
    )


# ------------------------------------------------------------
# 3. P(3,2) filter (optional helper)
# ------------------------------------------------------------

def is_P32(n: int) -> bool:
    """
    Very simple P(3,2)-style filter:
    here we only enforce that n is not divisible by 2, 3, or 5.

    In the Collatz-5 context, such numbers tend to behave like
    'elite racers' on the Outer Circuit.
    """
    if n <= 0:
        return False
    return (n % 2 != 0) and (n % 3 != 0) and (n % 5 != 0)


def generate_P32_in_range(start: int, end: int) -> Iterable[int]:
    """
    Generate integers n in [start, end] that satisfy is_P32(n).
    """
    for n in range(start, end + 1):
        if is_P32(n):
            return n


# ------------------------------------------------------------
# 4. Simple command-line demo
# ------------------------------------------------------------

def demo_range(a: int, b: int) -> None:
    """
    Explore Collatz-5 for n in [a, b] and print basic stats.

    This is a simple text-based exploration tool.
    """
    print(f"Collatz-5 demo for n in [{a}, {b}]")
    print("n, steps, laps, max_value, classification")
    for n in range(a, b + 1):
        stats = collatz5_orbit(n)
        print(f"{n}, {stats.steps}, {stats.laps}, {stats.max_value}, {stats.classification()}")


def demo_single(n: int) -> None:
    """
    Show the orbit and stats for a single n.
    """
    stats = collatz5_orbit(n)
    print(f"Start n = {stats.start}")
    print(f"Orbit: {stats.orbit}")
    print(f"Steps      : {stats.steps}")
    print(f"Laps       : {stats.laps}")
    print(f"Max value  : {stats.max_value}")
    print(f"Class      : {stats.classification()}")


if __name__ == "__main__":
    # Example usage:
    #   python collatz5_pentadica.py
    #   (edit the values below as you like)

    # 1) Single example: n = 161 (used in the Overview)
    print("=== Example: n = 161 ===")
    demo_single(161)
    print()

    # 2) Small range demo
    print("=== Demo range: n = 1..30 ===")
    demo_range(1, 30)
    print()

    # 3) Example of a known 'elite racer' (P(3,2) style)
    n_legendary = 774_840_977
    print(f"=== Example: n = {n_legendary} (Legendary Glider candidate) ===")
    demo_single(n_legendary)

